DROP TABLE IF EXISTS countries;

CREATE TABLE countries(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100), data VARCHAR(100));

DROP TABLE IF EXISTS states;

CREATE TABLE states(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100), count VARCHAR(100), co_id BIGINT );

DROP TABLE IF EXISTS towns;

CREATE TABLE towns(town_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100), people_count VARCHAR(100), st_id BIGINT);